#!/usr/bin/env bash
# Installer for the Terminator "Styler" plugin and the degauss command.
#
# Usage:
#   bash install.sh             # install (or update)
#   bash install.sh --uninstall # remove the plugin and the command

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_SRC="$SCRIPT_DIR/styler.py"
PLUGIN_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/terminator/plugins"
PLUGIN_DST="$PLUGIN_DIR/styler.py"
DEGAUSS_SRC="$SCRIPT_DIR/degauss.py"
BIN_DIR="$HOME/.local/bin"
DEGAUSS_DST="$BIN_DIR/degauss"
HOOK_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/degauss"
HOOK_DST="$HOOK_DIR/hook.bash"

# Files left behind by the old standalone plugins this one replaces.
LEGACY_PLUGINS=(
    "$PLUGIN_DIR/titlebar_changer.py"
    "$PLUGIN_DIR/profile_switcher.py"
    "$PLUGIN_DIR/window_styler.py"
    "$PLUGIN_DIR/maximise_aware.py"
    "$PLUGIN_DIR/degauss_plugin.py"
)

backup() {
    local backup_path
    backup_path="$1.bak.$(date +%Y%m%d-%H%M%S)"
    cp -p "$1" "$backup_path"
    echo "Backed up existing $1 to $backup_path"
}

if [[ "${1:-}" == "--uninstall" ]]; then
    removed=0
    for f in "$PLUGIN_DST" "$DEGAUSS_DST" "$HOOK_DST"; do
        if [[ -f "$f" ]]; then
            rm -f "$f"
            echo "Removed $f"
            removed=1
        fi
    done
    if (( removed )); then
        echo "Disable 'TerminatorStyler' in Terminator > Preferences > Plugins,"
        echo "then restart Terminator."
    else
        echo "Nothing to remove (no $PLUGIN_DST, no $DEGAUSS_DST)."
    fi
    rmdir "$HOOK_DIR" 2>/dev/null || true
    echo "Remove the '. $HOOK_DST' line from your bash startup file, if any."
    exit 0
fi

for f in "$PLUGIN_SRC" "$DEGAUSS_SRC"; do
    if [[ ! -f "$f" ]]; then
        echo "Error: $f not found" >&2
        exit 1
    fi
done

if ! command -v terminator >/dev/null 2>&1; then
    echo "Warning: 'terminator' not found in PATH." >&2
    echo "         Installing the plugin file anyway." >&2
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "Error: 'python3' is required." >&2
    exit 1
fi

for f in "$PLUGIN_SRC" "$DEGAUSS_SRC"; do
    if ! python3 -c 'import ast, sys; ast.parse(open(sys.argv[1]).read())' "$f"; then
        echo "Error: $f failed Python syntax check." >&2
        exit 1
    fi
done

mkdir -p "$PLUGIN_DIR" "$BIN_DIR"

install_file() {
    local src="$1" dst="$2" mode="$3"
    if [[ -f "$dst" ]] && ! cmp -s "$src" "$dst"; then
        backup "$dst"
    fi
    install -m "$mode" "$src" "$dst"
}

install_file "$PLUGIN_SRC" "$PLUGIN_DST" 644
install_file "$DEGAUSS_SRC" "$DEGAUSS_DST" 755

mkdir -p "$HOOK_DIR"
{
    echo "# Generated by terminator-styler install.sh; re-run it to update."
    "$DEGAUSS_DST" --shell-init
} > "$HOOK_DST.tmp"
mv "$HOOK_DST.tmp" "$HOOK_DST"

# Warn (don't auto-remove) about the legacy plugin files.
legacy_found=()
for f in "${LEGACY_PLUGINS[@]}"; do
    if [[ -f "$f" ]]; then
        legacy_found+=("$f")
    fi
done

cat <<MSG

Installed: $PLUGIN_DST
           $DEGAUSS_DST
           $HOOK_DST

Next steps:
  1. (Re)start Terminator -- plugins are only scanned at startup.
  2. Open Preferences > Plugins, enable 'TerminatorStyler'
     (and disable any of the old plugins it replaces).
  3. Right-click any terminal > Styler Preferences...
     to configure each feature (one tab per feature).
  4. Run 'degauss' in a pane, or right-click > Degauss this pane.
  5. To degauss on typos, add this line to ~/.bash_aliases (or ~/.bashrc):
       . $HOOK_DST

Settings from the four old plugins are migrated automatically the first
time TerminatorStyler loads. The migration only runs once.

MSG

if (( ${#legacy_found[@]} > 0 )); then
    cat <<MSG
The following legacy plugin files are still present and should be removed
or disabled once you have verified that TerminatorStyler works:

MSG
    printf '  %s\n' "${legacy_found[@]}"
    cat <<MSG

Remove them with:
  rm ${legacy_found[*]}

Then disable the old plugin names in Terminator > Preferences > Plugins:
  TitlebarChanger, ProfileSwitcher, WindowStyler, MaximiseAware, Degauss

MSG
fi

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "Note: $BIN_DIR is not in PATH; add it to run 'degauss'." ;;
esac
